version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd eureka-server
      - mvn clean package
      - echo Building the docker image
      - docker build -t eureka-server .
      - docker tag rcrounak/eureka-server:latest public.ecr.aws/p2e3u7x0/pension-management-system-896073:eureka--server
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push public.ecr.aws/p2e3u7x0/pension-management-system-896073:eureka-server