# server properties
server:
 port: 8083

# spring properties
spring:
 application:
  name: PENSIONER-DETAIL-SERVICE
  
#Eureka client
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # add public IP link here
      defaultZone: http://localhost:8761/eureka/ 

# Error Messages
errorMessage: Aadhaar Number Not Found